const $=id=>document.getElementById(id);
let config, report;
const percent=x=>x===null?'N/A':`${(x*100).toFixed(1)}%`;
const labels={supported:'Supported in this pack',contradicted:'Contradicted in this pack',valid_variant:'Valid variant in this pack',unresolved:'Unresolved'};
const node=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-BhashaGuard-Token':config.token},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error||'Local request failed');return result;}
function display(r){report=r;$('empty').hidden=true;$('report').hidden=false;
 $('risk').textContent=`${r.risk.level.replaceAll('_',' ')}. ${r.pack.kind==='synthetic_fixture'?'Synthetic fixture findings, not a real-world cultural verdict.':'Findings are scoped to the supplied evidence pack.'}`;
 $('metrics').replaceChildren();for(const [k,v]of [['Script fidelity',percent(r.script.ratio)],['Evidence consistency',percent(r.metrics.consistency)],['Evidence coverage',percent(r.metrics.coverage)],['Unresolved claims',String(r.metrics.unresolved)]]){$('metrics').append(node('dt',k),node('dd',v));}
 $('claims').replaceChildren();const entries=new Map(r.evidence.map(e=>[e.id,e]));
 for(const c of r.claims){const a=node('article','','finding');a.dataset.status=c.status;a.append(node('strong',labels[c.status]),node('p',c.text),node('p',c.reason));
  for(const id of c.evidence_ids){const e=entries.get(id);a.append(node('blockquote',e.excerpt),node('p',e.translation_en,'source'),node('p',`${id} · ${e.locale} · ${e.license} · ${e.reviewed_on}`,'source'));if(/^https?:\/\//.test(e.source_url)){const link=node('a',e.source_title);link.href=e.source_url;link.target='_blank';link.rel='noopener noreferrer';a.append(link);}else a.append(node('p',`${e.source_title}: ${e.source_url}`,'source'));}
  if(!c.evidence_ids.length&&c.retrieval.length){const d=document.createElement('details');d.append(node('summary','Retrieved candidates (not verification)'));for(const hit of c.retrieval){const e=entries.get(hit.id);d.append(node('p',`${hit.id}: ${e.excerpt}`));}a.append(d);}
  $('claims').append(a);
 }
 $('script').textContent=`${r.script.target_count}/${r.script.assessed_count} assessed alphabetic code points use the target script. Excluded Latin: ${r.script.excluded_latin_count}. Issues: ${r.script.violations.slice(0,20).map(v=>`${v.character} at ${v.offset}`).join(', ')||'none'}. Offsets count Unicode code points.`;
 $('runtime').textContent=`${r.runtime.backend} · ${r.runtime.guard_latency_ms} ms guard time · NPU used: ${r.runtime.npu_used}. Pack ${r.pack.version}. Model loading excluded.`;
}
$('analyze').onclick=async()=>{$('message').textContent='';$('analyze').disabled=true;try{display(await api('/api/analyze',{text:$('answer').value,prompt:$('prompt').value,language:$('language').value,locale:$('locale').value,allow_latin:$('latin').checked}));}catch(e){$('message').textContent=e.message;}finally{$('analyze').disabled=false;}};
$('generate').onclick=async()=>{$('message').textContent='Generating on the configured local server…';$('generate').disabled=true;try{const r=await api('/api/generate',{prompt:$('prompt').value,language:$('language').value});$('answer').value=r.text;$('message').textContent=r.backend;}catch(e){$('message').textContent=e.message;}finally{$('generate').disabled=false;}};
$('demo').onchange=()=>{const c=config.demo_cases.find(c=>c.id===$('demo').value);if(!c)return;$('answer').value=c.text;$('language').value=c.language;$('locale').value=c.locale;$('prompt').value=c.prompt;$('translation').textContent=`Fixture English gloss: ${c.translation_en}`;};
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('json').onclick=()=>download('bhashaguard-report.json',JSON.stringify(report,null,2),'application/json');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('html').onclick=()=>{if(!report)return;const content=`<!doctype html><html lang="en"><meta charset="utf-8"><title>BhashaGuard review report</title><body><h1>BhashaGuard Edge</h1><p>Evidence pack: ${esc(report.pack.kind)}. ${esc(report.risk.level)}.</p><p>Script fidelity: ${percent(report.script.ratio)}. Evidence coverage: ${percent(report.metrics.coverage)}.</p>${report.claims.map(c=>`<h2>${esc(labels[c.status])}</h2><p>${esc(c.text)}</p><p>${esc(c.reason)}</p>${c.evidence_ids.map(id=>{const e=report.evidence.find(e=>e.id===id);return `<blockquote>${esc(e.excerpt)}</blockquote><p>${esc(e.source_title)}: ${esc(e.source_url)}</p>`;}).join('')}`).join('')}<h2>Full report and provenance</h2><pre>${esc(JSON.stringify(report,null,2))}</pre></body></html>`;download('bhashaguard-report.html',content,'text/html');};
fetch('/api/config').then(r=>r.json()).then(c=>{config=c;$('pack-status').textContent=c.pack_kind==='synthetic_fixture'?'Demo pack: invented examples for testing. No real cultural facts or benchmark accuracy are claimed.':'Custom evidence pack. Review its sources and coverage before relying on findings.';$('generate').hidden=!c.generation_enabled;for(const d of c.demo_cases){const o=node('option',d.title);o.value=d.id;$('demo').append(o);}}).catch(()=>{$('message').textContent='Could not load local configuration.';});
